PROJECT = imcron
PROJECT_DESCRIPTION = New project
# PROJECT_VERSION # 继承更目录版本号

# Whitespace to be used when creating files from templates.
SP = 4

# Make sure we know where the applications are located.
ROOT_DIR ?= ../..
APPS_DIR ?= ..
DEPS_DIR ?= ../../deps

include $(ROOT_DIR)/erlang.mk
