# Generated by Erlang.mk. Edit at your own risk!

src/api/handler/chat_handler.erl:: include/imboy.hrl; @touch $@
src/api/handler/friend_handler.erl:: include/imboy.hrl; @touch $@
src/api/handler/passport_handler.erl:: include/imboy.hrl; @touch $@
src/api/handler/websocket_handler.erl:: include/imboy.hrl; @touch $@
src/application/service/friend_as.erl:: include/imboy.hrl; @touch $@
src/application/service/websocket_as.erl:: include/imboy.hrl; @touch $@
src/domain/service/chat_message_ds.erl:: include/imboy.hrl; @touch $@
src/domain/service/friend_category_ds.erl:: include/imboy.hrl; @touch $@
src/domain/service/friend_ds.erl:: include/imboy.hrl; @touch $@
src/domain/service/token_ds.erl:: include/imboy.hrl; @touch $@
src/domain/service/user_ds.erl:: include/imboy.hrl; @touch $@
src/domain/service/websocket_ds.erl:: include/imboy.hrl; @touch $@
src/infrastructure/imboy_cipher.erl:: include/imboy.hrl; @touch $@
src/infrastructure/imboy_db.erl:: include/imboy.hrl; @touch $@
src/infrastructure/middleware/auth_middleware.erl:: include/imboy.hrl; @touch $@
src/infrastructure/repository/chat_message_repo.erl:: include/imboy.hrl; @touch $@
src/infrastructure/repository/websocket_store_repo.erl:: include/imboy.hrl; @touch $@

COMPILE_FIRST +=
