# Generated by Erlang.mk. Edit at your own risk!

src/api/handler/passport_handler.erl:: include/imboy.hrl; @touch $@
src/domain/service/token_ds.erl:: include/imboy.hrl; @touch $@
src/infrastructure/imboy_cipher.erl:: include/imboy.hrl; @touch $@

COMPILE_FIRST +=
