# Generated by Erlang.mk. Edit at your own risk!

src/applications/api/assembler/friend_myfriend_aas.erl:: include/common.hrl; @touch $@
src/applications/api/handler/conversation_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/friend_category_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/friend_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/group_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/init_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/passport_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/stress_testing_ws_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/user_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/websocket_handler.erl:: include/common.hrl; @touch $@
src/applications/api/handler/ws_handler.erl:: include/common.hrl; @touch $@
src/applications/api/repository/chat_store_repo.erl:: include/common.hrl; @touch $@
src/applications/api/repository/dialog_msg_repo.erl:: include/common.hrl; @touch $@
src/applications/api/repository/friend_repo.erl:: include/common.hrl; @touch $@
src/applications/api/repository/group_msg_repo.erl:: include/chat.hrl include/common.hrl; @touch $@
src/applications/api/repository/group_msg_timeline_repo.erl:: include/common.hrl; @touch $@
src/applications/api/repository/user_repo.erl:: include/common.hrl; @touch $@
src/applications/api/repository/user_setting_repo.erl:: include/common.hrl; @touch $@
src/applications/api/service/dialog_msg_as.erl:: include/chat.hrl include/common.hrl; @touch $@
src/applications/api/service/friend_as.erl:: include/common.hrl; @touch $@
src/applications/api/service/friend_category_as.erl:: include/common.hrl; @touch $@
src/applications/api/service/group_as.erl:: include/common.hrl; @touch $@
src/applications/api/service/group_msg_as.erl:: include/chat.hrl include/common.hrl; @touch $@
src/applications/api/service/user_as.erl:: include/common.hrl; @touch $@
src/applications/api/service/websocket_as.erl:: include/common.hrl; @touch $@
src/domain/service/dialog_msg_ds.erl:: include/chat.hrl include/common.hrl; @touch $@
src/domain/service/friend_category_ds.erl:: include/common.hrl; @touch $@
src/domain/service/friend_ds.erl:: include/common.hrl; @touch $@
src/domain/service/group_ds.erl:: include/common.hrl; @touch $@
src/domain/service/group_member_ds.erl:: include/common.hrl; @touch $@
src/domain/service/group_msg_ds.erl:: include/common.hrl; @touch $@
src/domain/service/message_ds.erl:: include/common.hrl; @touch $@
src/domain/service/token_ds.erl:: include/common.hrl; @touch $@
src/domain/service/user_ds.erl:: include/common.hrl; @touch $@
src/domain/service/user_setting_ds.erl:: include/common.hrl; @touch $@
src/domain/service/websocket_ds.erl:: include/common.hrl; @touch $@
src/domain/translator/hashids_tlt.erl:: include/hashids.hrl; @touch $@
src/imboy_app.erl:: include/common.hrl; @touch $@
src/infrastructure/func.erl:: include/common.hrl; @touch $@
src/infrastructure/imboy_cipher.erl:: include/common.hrl; @touch $@
src/infrastructure/middleware/auth_middleware.erl:: include/common.hrl; @touch $@
src/infrastructure/mysql_pool.erl:: include/common.hrl; @touch $@
src/infrastructure/server/offline_server.erl:: include/chat.hrl include/common.hrl; @touch $@
src/infrastructure/server/user_server.erl:: include/common.hrl; @touch $@
src/infrastructure/util/password_util.erl:: include/common.hrl; @touch $@

COMPILE_FIRST +=
