PROJECT = imlib
PROJECT_DESCRIPTION = 基于cowboy的一款即时聊天软件 基础模块，被本项目其他应用依赖
PROJECT_VERSION = 0.1.15

# Whitespace to be used when creating files from templates.
SP = 4

# Make sure we know where the applications are located.
ROOT_DIR ?= ../..
APPS_DIR ?= ..
DEPS_DIR ?= ../../deps

include $(ROOT_DIR)/erlang.mk
