PROJECT = imadm
PROJECT_DESCRIPTION = IMBoy 简单的管理后台用用
PROJECT_VERSION = 0.1.2

# Whitespace to be used when creating files from templates.
SP = 4

# Make sure we know where the applications are located.
ROOT_DIR ?= ../..
APPS_DIR ?= ..
DEPS_DIR ?= ../../deps

include $(ROOT_DIR)/erlang.mk
