-- E2EE-2026-012 / Task 8 (LT-03)：统一群历史 join boundary
-- 当前实现语义：F2（仅入群后）+ R2（每次重入新世代）+ D3（archive ACL 账号级，key 显式恢复）+ M1（存量 active 祖传 start_seq=1）；用户批准证据缺失。
-- 边界一律以 conv_seq（消息持久接受顺序）表达，禁止 wall-clock 推断。
-- 迁移必须可逆、可审计并记录所选 M 策略（见文件尾 COMMENT）。

-- 1) 世代表：append-only，leave/remove/workspace_remove 关闭当前世代，rejoin append 新世代
CREATE TABLE public.group_member_generation (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id      bigint NOT NULL,
    user_id       bigint NOT NULL,
    generation_no integer NOT NULL DEFAULT 1,
    start_seq     bigint NOT NULL,
    end_seq       bigint,
    close_reason  text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_gmg_generation UNIQUE (group_id, user_id, generation_no),
    -- 世代区间 [start_seq, end_seq]；start_seq=加入时计数器+1（下一分配值），
    -- end_seq=离开时计数器现值。离开时计数器未越过 start_seq-1（入群后零消息）
    -- 即空区间，end_seq=start_seq-1 合法（成员未见过任何消息）。
    CONSTRAINT ck_gmg_interval CHECK (end_seq IS NULL OR end_seq >= start_seq - 1)
);

CREATE INDEX idx_gmg_group_user_open
    ON public.group_member_generation (group_id, user_id)
    WHERE end_seq IS NULL;

-- 同一成员至多一个 open 世代（部分唯一索引，重复 join 幂等兜底）
CREATE UNIQUE INDEX uq_gmg_one_open_generation
    ON public.group_member_generation (group_id, user_id)
    WHERE end_seq IS NULL;

-- 2) staging 预分配列：接受事务写 staging 时固化 conv_seq；legacy 行允许 NULL（由 backfill 或归档期补齐，仅 c2c）
-- ⚠️ msg_store_staging 表不由迁移创建（见 00000048 同款约束）：全新安装时该表由
--    src/repo/msg_store_repo.erl ensure_table_exists/0 在迁移之后运行时创建，
--    conv_seq 列由那段 DDL 覆盖（两处必须同步，守护用例见
--    group_history_boundary_tests:ensure_table_ddl_has_conv_seq_test/0）；
--    本迁移用 IF EXISTS 只覆盖存量部署，不得阻断首次启动。
ALTER TABLE IF EXISTS public.msg_store_staging
    ADD COLUMN IF NOT EXISTS conv_seq bigint;

-- 3) M1 兼容回填：存量 active 成员（status=1）祖传 start_seq=1，新加入/重入开始严格执行
INSERT INTO public.group_member_generation (group_id, user_id, generation_no, start_seq, end_seq, close_reason)
SELECT gm.group_id, gm.user_id, 1, 1, NULL, NULL
FROM public.group_member gm
WHERE gm.status = 1
ON CONFLICT DO NOTHING;

-- 4) legacy staging backlog 补齐（§7.6）：c2g 行按 staging id 升序（=持久接受顺序的稳定代理）
--    逐 conv_key 原子推进计数器并回填；c2c 行保持 NULL（c2c 无成员边界，归档期分配为既有行为）。
--    全新安装时 staging 表尚不存在（运行时才建）且无 legacy 行可回填，整段跳过。
DO $$
DECLARE
    r record;
    base bigint;
BEGIN
    IF to_regclass('public.msg_store_staging') IS NULL THEN
        RETURN;
    END IF;
    FOR r IN
        SELECT to_id::text AS gid, count(*) AS cnt
        FROM public.msg_store_staging
        WHERE type = 'c2g' AND conv_seq IS NULL AND to_id IS NOT NULL
        GROUP BY to_id
    LOOP
        SELECT COALESCE(max(seq), 0) INTO base
        FROM public.msg_store_seq WHERE conv_key = 'c2g:' || r.gid;

        UPDATE public.msg_store_seq SET seq = base + r.cnt
        WHERE conv_key = 'c2g:' || r.gid;
        IF NOT FOUND THEN
            INSERT INTO public.msg_store_seq (conv_key, seq)
            VALUES ('c2g:' || r.gid, base + r.cnt)
            ON CONFLICT (conv_key) DO UPDATE SET seq = EXCLUDED.seq;
        END IF;

        WITH ordered AS (
            SELECT id, row_number() OVER (ORDER BY id) AS rn
            FROM public.msg_store_staging
            WHERE type = 'c2g' AND conv_seq IS NULL AND to_id::text = r.gid
        )
        UPDATE public.msg_store_staging s
        SET conv_seq = base + ordered.rn
        FROM ordered
        WHERE s.id = ordered.id;
    END LOOP;
END $$;

COMMENT ON TABLE public.group_member_generation
    IS 'E2EE-2026-012 join boundary; migration policy = M1 (legacy active members grandfathered start_seq=1)';
