DROP TABLE IF EXISTS public."channel_price" CASCADE;
DROP TABLE IF EXISTS public."channel_invitation" CASCADE;
DROP TABLE IF EXISTS public."channel_order" CASCADE;
DROP INDEX IF EXISTS idx_channel_price_channel_id;
DROP INDEX IF EXISTS idx_channel_price_status;
DROP INDEX IF EXISTS idx_channel_invitation_channel_id;
DROP INDEX IF EXISTS idx_channel_invitation_inviter_uid;
DROP INDEX IF EXISTS idx_channel_invitation_invitee_uid;
DROP INDEX IF EXISTS idx_channel_invitation_status;
DROP INDEX IF EXISTS idx_channel_invitation_code;
DROP INDEX IF EXISTS idx_channel_invitation_invitee_pending;
DROP INDEX IF EXISTS idx_channel_invitation_channel_active;
DROP INDEX IF EXISTS idx_channel_order_channel_id;
DROP INDEX IF EXISTS idx_channel_order_user_id;
DROP INDEX IF EXISTS idx_channel_order_order_no;
DROP INDEX IF EXISTS idx_channel_order_status;
DROP INDEX IF EXISTS idx_channel_order_payment_no;
DROP INDEX IF EXISTS idx_channel_order_user_status;
DROP INDEX IF EXISTS idx_channel_order_channel_paid;
DROP FUNCTION IF EXISTS public.fn_channel_subscribe_updated_at;
DROP FUNCTION IF EXISTS public.fn_channel_invitation_accept;
DROP FUNCTION IF EXISTS public.cleanup_expired_channel_invitations;
DROP FUNCTION IF EXISTS public.cleanup_expired_channel_orders;
DROP FUNCTION IF EXISTS public.generate_channel_order_no;
DROP FUNCTION IF EXISTS public.generate_channel_invitation_code;
DROP TRIGGER IF EXISTS tr_channel_price_updated_at ON public."channel_price";
DROP TRIGGER IF EXISTS tr_channel_invitation_updated_at ON public."channel_invitation";
DROP TRIGGER IF EXISTS tr_channel_order_updated_at ON public."channel_order";
DROP TRIGGER IF EXISTS tr_channel_invitation_accept ON public."channel_invitation";
