DROP TABLE IF EXISTS public."e2ee_transfer_sessions" CASCADE;
DROP TABLE IF EXISTS public."e2ee_trusted_contacts" CASCADE;
DROP TABLE IF EXISTS public."e2ee_key_shares" CASCADE;
DROP TABLE IF EXISTS public."e2ee_social_shards" CASCADE;
DROP TABLE IF EXISTS public."e2ee_local_backups" CASCADE;
DROP TABLE IF EXISTS public."e2ee_shard_transmission_log" CASCADE;
DROP INDEX IF EXISTS idx_e2ee_transfer_sessions_session_id;
DROP INDEX IF EXISTS idx_e2ee_transfer_sessions_from_uid;
DROP INDEX IF EXISTS idx_e2ee_transfer_sessions_to_uid;
DROP INDEX IF EXISTS idx_e2ee_transfer_sessions_status;
DROP INDEX IF EXISTS idx_e2ee_transfer_sessions_expires_at;
DROP INDEX IF EXISTS idx_e2ee_transfer_sessions_to_uid_status_expires;
DROP INDEX IF EXISTS idx_e2ee_transfer_sessions_unique_active;
DROP INDEX IF EXISTS idx_e2ee_trusted_contacts_uid;
DROP INDEX IF EXISTS idx_e2ee_trusted_contacts_contact_uid;
DROP INDEX IF EXISTS idx_e2ee_trusted_contacts_status;
DROP INDEX IF EXISTS idx_e2ee_key_shares_owner_uid;
DROP INDEX IF EXISTS idx_e2ee_key_shares_trustee_uid;
DROP INDEX IF EXISTS idx_e2ee_key_shares_share_index;
DROP INDEX IF EXISTS idx_e2ee_social_shards_uid;
DROP INDEX IF EXISTS idx_e2ee_social_shards_proxy_uid;
DROP INDEX IF EXISTS idx_e2ee_social_shards_key_version;
DROP INDEX IF EXISTS idx_e2ee_social_shards_shard_id;
DROP INDEX IF EXISTS idx_e2ee_social_shards_status;
DROP INDEX IF EXISTS idx_e2ee_social_shards_user_active;
DROP INDEX IF EXISTS idx_e2ee_social_shards_proxy_active;
DROP INDEX IF EXISTS idx_e2ee_social_shards_unique_active;
DROP INDEX IF EXISTS idx_e2ee_local_backups_uid;
DROP INDEX IF EXISTS idx_e2ee_local_backups_device_id;
DROP INDEX IF EXISTS idx_e2ee_local_backups_created_at;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_shard_id;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_key_version;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_uid;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_proxy_uid;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_action;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_created_at;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_shard_action_time;
DROP INDEX IF EXISTS idx_e2ee_shard_transmission_log_uid_time;
DROP INDEX IF EXISTS idx_user_device_key_id;
DROP FUNCTION IF EXISTS public.update_e2ee_updated_at;
DROP FUNCTION IF EXISTS public.cleanup_expired_transfer_sessions;
DROP FUNCTION IF EXISTS public.cleanup_used_social_shards;
DROP FUNCTION IF EXISTS public.check_e2ee_shard_transmission_anomaly;
DROP FUNCTION IF EXISTS public.cleanup_old_shard_transmission_logs;
DROP TRIGGER IF EXISTS trg_e2ee_transfer_sessions_updated_at ON public."e2ee_transfer_sessions";
DROP TRIGGER IF EXISTS trg_e2ee_trusted_contacts_updated_at ON public."e2ee_trusted_contacts";
DROP TRIGGER IF EXISTS trg_e2ee_key_shares_updated_at ON public."e2ee_key_shares";
ALTER TABLE public."user_device" DROP COLUMN IF EXISTS "key_id";
