DROP TABLE IF EXISTS public."msg_s2c" CASCADE;
DROP INDEX IF EXISTS i_s2c_action;
DROP INDEX IF EXISTS i_s2c_ToId;
DROP INDEX IF EXISTS i_s2c_FromId;
DROP INDEX IF EXISTS i_s2c_MsgType;
DROP INDEX IF EXISTS i_s2c_e2ee;
