DROP INDEX IF EXISTS idx_moment_post_active_id_desc;
DROP INDEX IF EXISTS idx_moment_post_author_active_id_desc;
DROP INDEX IF EXISTS idx_moment_comment_post_active_id_desc;
DROP INDEX IF EXISTS idx_moment_report_pending_id_desc;
DROP INDEX IF EXISTS idx_moment_timeline_recipient_active_id_desc;
DROP INDEX IF EXISTS idx_moment_like_post_id_desc;

DROP TABLE IF EXISTS public."moment_post" CASCADE;
DROP TABLE IF EXISTS public."moment_post_acl" CASCADE;
DROP TABLE IF EXISTS public."moment_timeline" CASCADE;
DROP TABLE IF EXISTS public."moment_like" CASCADE;
DROP TABLE IF EXISTS public."moment_comment" CASCADE;
DROP TABLE IF EXISTS public."moment_report" CASCADE;
DROP INDEX IF EXISTS idx_moment_post_author_created;
DROP INDEX IF EXISTS idx_moment_post_status_created;
DROP INDEX IF EXISTS idx_moment_post_visibility_status;
DROP INDEX IF EXISTS idx_moment_post_acl_post;
DROP INDEX IF EXISTS idx_moment_post_acl_uid;
DROP INDEX IF EXISTS idx_moment_timeline_uid_rank;
DROP INDEX IF EXISTS idx_moment_timeline_author;
DROP INDEX IF EXISTS idx_moment_like_post_created;
DROP INDEX IF EXISTS idx_moment_like_user_created;
DROP INDEX IF EXISTS idx_moment_comment_post_created;
DROP INDEX IF EXISTS idx_moment_comment_user_created;
DROP INDEX IF EXISTS idx_moment_report_status_created;
DROP INDEX IF EXISTS idx_moment_report_post;
DROP FUNCTION IF EXISTS public.fn_moment_touch_updated_at;
DROP TRIGGER IF EXISTS tr_moment_post_updated_at ON public."moment_post";
DROP TRIGGER IF EXISTS tr_moment_comment_updated_at ON public."moment_comment";
DROP TRIGGER IF EXISTS tr_moment_report_updated_at ON public."moment_report";
