DROP INDEX IF EXISTS i_channel_message_revoked;
ALTER TABLE public."channel_message" DROP COLUMN IF EXISTS "revoked";

DROP TABLE IF EXISTS public."channel" CASCADE;
DROP TABLE IF EXISTS public."channel_subscription" CASCADE;
DROP TABLE IF EXISTS public."channel_message" CASCADE;
DROP TABLE IF EXISTS public."channel_admin" CASCADE;
DROP TABLE IF EXISTS public."channel_stats_daily" CASCADE;
DROP TABLE IF EXISTS public."channel_message_view" CASCADE;
DROP TABLE IF EXISTS public."channel_reaction" CASCADE;
DROP INDEX IF EXISTS i_channel_creator_uid;
DROP INDEX IF EXISTS i_channel_status_created;
DROP INDEX IF EXISTS i_channel_subscriber_count;
DROP INDEX IF EXISTS i_channel_custom_id;
DROP INDEX IF EXISTS i_channel_subscription_user;
DROP INDEX IF EXISTS i_channel_subscription_channel;
DROP INDEX IF EXISTS i_channel_message_channel_created;
DROP INDEX IF EXISTS i_channel_message_author;
DROP INDEX IF EXISTS i_channel_message_pinned;
DROP INDEX IF EXISTS i_channel_admin_user;
DROP INDEX IF EXISTS i_channel_stats_daily_channel;
DROP INDEX IF EXISTS i_channel_stats_daily_date;
DROP INDEX IF EXISTS i_channel_message_view_message;
DROP INDEX IF EXISTS i_channel_message_view_channel_user;
DROP INDEX IF EXISTS i_channel_message_view_viewed_at;
DROP INDEX IF EXISTS i_channel_reaction_message;
DROP INDEX IF EXISTS i_channel_reaction_channel;
DROP INDEX IF EXISTS i_channel_reaction_user;
DROP INDEX IF EXISTS i_channel_reaction_type;
DROP FUNCTION IF EXISTS public.fn_update_channel_message_view_count;
DROP FUNCTION IF EXISTS public.fn_update_channel_message_reaction_summary;
DROP TRIGGER IF EXISTS tr_update_channel_message_view_count ON public."channel_message_view";
DROP TRIGGER IF EXISTS tr_update_channel_message_reaction_summary ON public."channel_reaction";
