DROP TABLE IF EXISTS public."system_datacenter" CASCADE;
DROP TABLE IF EXISTS public."system_id_segment" CASCADE;
DROP TABLE IF EXISTS public."system_datacenter_log" CASCADE;
DROP TABLE IF EXISTS public."system_id_segment_stats" CASCADE;
DROP INDEX IF EXISTS i_datacenter_active;
DROP INDEX IF EXISTS i_datacenter_region;
DROP INDEX IF EXISTS i_id_segment_dc_table;
DROP INDEX IF EXISTS uk_datacenter_table_active;
DROP INDEX IF EXISTS i_id_segment_active;
DROP INDEX IF EXISTS i_id_segment_table;
DROP INDEX IF EXISTS i_id_segment_allocated_at;
DROP INDEX IF EXISTS i_dclog_dc_id;
DROP INDEX IF EXISTS i_dclog_action;
DROP INDEX IF EXISTS i_dclog_created_at;
DROP INDEX IF EXISTS i_idstats_dc_table_time;
DROP FUNCTION IF EXISTS public.register_datacenter;
DROP FUNCTION IF EXISTS public.unregister_datacenter;
DROP FUNCTION IF EXISTS public.reactivate_datacenter;
DROP FUNCTION IF EXISTS public.get_or_allocate_id_segment;
DROP FUNCTION IF EXISTS public.init_sequence_from_segment;
DROP FUNCTION IF EXISTS public.init_all_sequences;
DROP FUNCTION IF EXISTS public.get_datacenter_segment_status;
DROP FUNCTION IF EXISTS public.renew_id_segment;
DROP FUNCTION IF EXISTS public.get_datacenters;
DROP FUNCTION IF EXISTS public.collect_id_segment_stats;
